### ISSUE TITLE
Lack of encrypt/decrypt documentation

### ISSUE THREAD

**Issue by Platonn** [btroncone/ngrx-store-localstorage#101]
Hi there!

I can see that encrypt/decrypt feature it's [already implemented](https://github.com/btroncone/ngrx-store-localstorage/blob/4f629bc25afc9ca7e911372b0374c66b0a3d11eb/src/index.ts#L61). However, I have problem to find a documentation for it. 

So maybe it would be good to update the [documentation of LocalStorageConfig](https://github.com/btroncone/ngrx-store-localstorage#localstorageconfig) and add encrypt/decrypt API there?

Many thanks,
Krzysztof

**Comment by nicolaspierre1990** [comment]
You ever managed to figure it out ? Having the same problem

**Comment by BBlackwo** [comment]
I've added the docs for this in the above PR. Thanks for raising this issue or I wouldn't have known this functionality existed!

**Comment by BBlackwo** [comment]
The docs have now been updated with the encrypt/decrypt information.
