### ISSUE TITLE
@ngrx/store 7.0.0 compatibility?

### ISSUE THREAD

**Issue by dstj** [btroncone/ngrx-store-localstorage#105]
Hi, I'm upgrading to NGRX 7.0 and I'm getting this warning:

```
npm WARN ngrx-store-localstorage@5.1.0 requires a peer of @ngrx/store@^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
```
Is `ngrx-store-localstorage` compatible with NGRX 7 and it's just a matter of updating the version requirements?

**Comment by bufke** [comment]
rehydrate seems broken with ngrx 7. Can anyone else confirm this?

**Comment by bufke** [comment]
This is resolved and just needs released to npm. Several people have mentioned it working in ngrx/store 7 so I think we are good to release. @btroncone fyi.

**Comment by btroncone** [comment]
@bufke Thanks for the help, I’ll release tonight! 👍👍

**Comment by Zeetah** [comment]
Still waiting on the npm release @btroncone

**Comment by btroncone** [comment]
This should be out now @zeetah, sorry for delay!
