### ISSUE TITLE
Changelog for v6.0.0?

### ISSUE THREAD

**Issue by Sturgelose** [btroncone/ngrx-store-localstorage#109]
Is there any Changelog for v6.0.0? Also, I assume this version aims to be compatible with RxJS v6.0.0, no?

**Comment by dstj** [comment]
Indeed, and a migration guide perhaps, because my state rehydration stopped working since I upgraded to 6.0.0 today (see [this issue](https://github.com/btroncone/ngrx-store-localstorage/issues/110))

**Comment by moniuch** [comment]
@dstj Please try 7.0.0 which was released two days ago. It contains #114. Hope it fixes your prblems. Let us know if it doesn't.

@btroncone Isn't this ticket actually one for having the changelog generation automated in this project?

**Comment by bufke** [comment]
I added a changelog for 8.0. Some versions don't have it. Going forward I'll try to maintain one as long as I'm helping on this project.
