### ISSUE TITLE
Rehydrate not working or lacks documentation or not supported yet

### ISSUE THREAD

**Issue by batousik** [btroncone/ngrx-store-localstorage#119]
NGRX/Store 7.3.0
ngrx-store-localstorage 7.0.0

Please explain how does the info get rehydrated from localstorage

When I hit refresh I get store and effects init actions that override data in store with default values, and data from localstorage gets overriden with them as well. 

Expected behavior as i thought from the readme is that ngrx-store-localstorage rehydrates these values upon browser refresh.

**Comment by PhilippMeissner** [comment]
Did you proactively set `rehydrate` to `true` in your config? If not, it defaults to `false` and will act as if the entire package was not used at all.

**Comment by batousik** [comment]
That worked, thanks!
