### ISSUE TITLE
Support for nrgx 8 / Angular 8?

### ISSUE THREAD

**Issue by dstj** [btroncone/ngrx-store-localstorage#129]
Hi,

ngrx 8.0.0 has a minimum dependency of Angular 8

> V8 has the minimum version requirements:

>Angular version 8.x
>Angular CLI version 8.0.2
>TypeScript version 3.4.x
>RxJS version 6.5.x

But ngrx-store-localstorage does not support it yet:

```
npm WARN ngrx-store-localstorage@7.0.0 requires a peer of @ngrx/store@^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
```

Any plans to update?

**Comment by isaacplmann** [comment]
It looks like the peer dependencies have been updated in package.json, but we need a new version pushed to npm.

Thanks!

**Comment by btroncone** [comment]
Just cut a new release for this, it should be available now 👍
