### ISSUE TITLE
can anyone help me how to use ngrx local storage to encrypt and decrpt data.

### ISSUE THREAD

**Issue by SADIK112** [btroncone/ngrx-store-localstorage#139]
export interface AutomobileState extends fromState.AppState {
    product: fromProduct.ProductState;
}

export function localStorageSyncReducer(reducer: ActionReducer<any>): ActionReducer<any> {
//     return localStorageSync({ keys: ['product'], rehydate: true})(reducer);
// }

// export const metaReducers: Array<MetaReducer<any, any>> = [localStorageSyncReducer];

**Comment by BBlackwo** [comment]
Hi @SADIK112, the docs have been updated with information on how to use the `decrypt`/`encrypt` functions. Does that help resolve your issue? If not, can you please provide more info.

See: https://github.com/btroncone/ngrx-store-localstorage#localstorageconfig

**Comment by BBlackwo** [comment]
@SADIK112, I'm closing this issue as I haven't heard back from you for a couple of months and don't have enough info to provide any more help. If you can provide more info feel free to re-open it.
