### ISSUE TITLE
Incorrect sync on load

### ISSUE THREAD

**Issue by qvantor** [btroncone/ngrx-store-localstorage#14]
For example, i add localStorageSync:
```
localStorageSync([{teamParams: ['category']}], true)'
```
And when i change key category it's create object in localstorage `{category: 'foo'}`, 
but when i reload page it replace my reducer init object on `{category: 'foo'}`, instead just adding category field in it.

**Comment by btroncone** [comment]
Just saw your PR, thanks! Let me review and I'll get back to you soon.

**Comment by btroncone** [comment]
This has been resolved in later versions. 👍
