### ISSUE TITLE
Saving nested state selectively (infinite depth)

### ISSUE THREAD

**Issue by bdspen** [btroncone/ngrx-store-localstorage#144]
In the `LocalStorageConfig`, when using the `keys` configuration property the property "app" will not be saved in the local storage at all, only the `deal` property in `clear` and the `auth` top level property.

Is this a problem with having the state nested too deeply? Or is my syntax wrong?

```
keys: [
      {
        clear: [
          {
            app: [
              "vehicles",
              "vehicle",
              "searchString",
              "writeupListLength",
              "selectedManagerId",
              "financing",
              "globalSettings",
              "dealer",
              "links",
              "deals",
              "newResiduals",
              "certUsedResiduals"
            ],
          },
          "deal"
        ]
      },
      "auth"
    ]
```

Using chrome on mac.

**Comment by BBlackwo** [comment]
Hi Ben @bdspen,

The `keys` config only works 2 levels deep. So you'll have to sync the whole  `app` object. E.g.

```
keys: [
  {
    clear: [
      "app", 
      "deal"
    ],
  },
  "auth",
]
```

Is there a reason you only want certain `app` properties saved to storage?

**Comment by bdspen** [comment]
> Is there a reason you only want certain `app` properties saved to storage?

Yes, I only want certain properties saved to storage because there is a "vehicles" property which has the potential to be quite large.

Since localStorage is limited to 5MB sometimes it goes over that limit, and it is only the vehicles property that is large enough to go over the limit.

It's nice to have it saved in local storage, to prevent having to make too many requests to the server for the vehicles.

It would be nice if the library was able to go deeper on the `keys` property, but maybe I can just move the `vehicles` key up one level on the same level as "app" and "deal" as a quick fix.

Thanks for clarifying that the keys only goes 2 levels deep. It would be helpful to put that in the docs if it isn't already.

**Comment by BBlackwo** [comment]
@bdspen thanks for all the info. 

I've updated the docs to clarify that it only goes 2 levels deep, would you mind having a look at #145? 

At this stage I don't see a lot of value in allowing the `keys` config to go deeper. Seems to me like going over the 5MB limit is an edge case. But if anyone else has this issue please add a comment to this issue and if enough people require this feature perhaps we can add it.

**Comment by bdspen** [comment]
#145 looks good.

If I might add, as a new user of the library I think it would be really nice to have more code examples of common configurations and usages of the library.

Something using `mergeReducer`, `storage`, and some of the other configurations like `serialize` and others in that list would be good too.

I did some experimenting with these properties to see what the library is capable of, but it would have been easier to look at some real world code samples.

Maybe there could be an examples folder with sample files?

**Comment by BBlackwo** [comment]
Thanks for having a look.

That's a great idea to provide more examples. I think we could add some more examples to the README for each of the config options as it's quite basic at the moment. Will add that to my todo list :) 

I'd be happy to review a PR if you had some time to provide more examples.

Closing this issue for now as I think it has been resolved.

**Comment by bdspen** [comment]
Sounds good. I'll see if I can whip up a few examples when I have time.

**Comment by BBlackwo** [comment]
Reopening this issue as someone has raised PR #165 Infinite depth configuration.
