### ISSUE TITLE
No release notes

### ISSUE THREAD

**Issue by qannoufoualid** [btroncone/ngrx-store-localstorage#148]
Please if you can make release notes with all changes in each version it would be great.
Thank you

**Comment by BBlackwo** [comment]
Hi @qannoufoualid we have a [CHANGELOG.md](https://github.com/btroncone/ngrx-store-localstorage/blob/master/CHANGELOG.md) that has changes, though it's missing a couple of versions in there sadly.

**Comment by BBlackwo** [comment]
Are you suggesting we use [Github Releases](https://github.com/btroncone/ngrx-store-localstorage/releases)?

**Comment by BBlackwo** [comment]
Closing this as I have had no response from @qannoufoualid.
