### ISSUE TITLE
Cookie as a storage

### ISSUE THREAD

**Issue by VladimirHumeniuk** [btroncone/ngrx-store-localstorage#152]
Is it possible to use cookie instead of localStorage? If so, is there any examples?

**Comment by BBlackwo** [comment]
No it is not possible to use cookies. Just `localStorage` and `sessionStorage`. See [Web Storage API interface](https://developer.mozilla.org/en-US/docs/Web/API/Storage).

Do you have a use-case that requires the use of cookies?
