### ISSUE TITLE
Problem with decrypt: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by VladimirHumeniuk** [btroncone/ngrx-store-localstorage#153]
I tried to encrypt/decrypt store to `localStorage` in the same way as it showed in documentation:

```
export function _localStorageSync(reducer: ActionReducer<any>): ActionReducer<any> {
  return localStorageSync({
    keys: [{
      'user': {
        encrypt: (state: string) => btoa(state),
        decrypt: (state: string) => atob(state)
      }
    }],
    rehydrate: true,
    removeOnUndefined: true,
    storage: localStorage,
  })(reducer);
}
```

But I got an error:
> Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

I tried to encode/decode the same data just in dev tools, and it's was working.

**Comment by BBlackwo** [comment]
Hi @VladimirHumeniuk, 

It sounds like you might need to clear out your localStorage and try again. What can happen is before you configure encrypt/decrypt it already has saved your data to localStorage *unencrypted*, so when it tries to decrypt it, it's not encrypted so it fails.

Here's an [example Stackblitz of encrypt/decrypt working](https://stackblitz.com/edit/ngrx-localstorage-153-encrypt-decrypt?file=src/app/store/metareducers.ts) which might help.
