### ISSUE TITLE
Multiple states in LocalStorage by a unique key

### ISSUE THREAD

**Issue by yurakhomitsky** [btroncone/ngrx-store-localstorage#159]
Is it possible to create several states in localStorage that are identified by a unique key?
For example 
![image](https://user-images.githubusercontent.com/54478076/85889412-188cb800-b7f4-11ea-9aea-e7a8c161e0c1.png)

**Comment by BBlackwo** [comment]
@yurakhomitsky you may be able to use the `storageKeySerializer` config option to do that.

**Comment by yurakhomitsky** [comment]
> @yurakhomitsky you may be able to use the `storageKeySerializer` config option to do that.

I have tried that option, as you can see on the picture, each key has unique id, that id defined by listening route params, then passing to the NgRx action, unfortunately I don't have acccess to action in `storageKeySerializer`
