### ISSUE TITLE
Incompatible peer dependency when "ng update @ngrx/store"

### ISSUE THREAD

**Issue by jorgeluis1706** [btroncone/ngrx-store-localstorage#166]
Hi, when i try to make "ng update @ngrx/store -C", it show me this message:

 Package "ngrx-store-localstorage" has an incompatible peer dependency to "@ngrx/store" (requires "^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0", would install "10.0.0").

Thanks!

**Comment by snider** [comment]
@btroncone compatibility issue with version 10 :)
