### ISSUE TITLE
Add (or detail) compatibility with Ionic Storage

### ISSUE THREAD

**Issue by pgcd** [btroncone/ngrx-store-localstorage#17]
I'm very much a newb here so maybe I'm missing something obvious, but I can't seem to use Ionic storage (https://ionicframework.com/docs/v2/storage/) with ngrx-store-localstorage, due to the fact that Ionic storage returns promises. 
I honestly have no idea how much work that would entail, and unfortunately I can't offer a PR either - on the other hand, if there's any simple way this can be done without touching your code, I believe it would be a very useful addition to the readme.

**Comment by florent1933** [comment]
Same, it will be usefull for my app.

**Comment by 99four** [comment]
Take a look at https://www.npmjs.com/package/ngrx-store-ionic-storage

**Comment by btroncone** [comment]
See #48 as well 👍
