### ISSUE TITLE
Data not stored in LocalStorage in production mode!

### ISSUE THREAD

**Issue by Ruslancic** [btroncone/ngrx-store-localstorage#171]
ngrx-store-localstorage is working fine in development mode, not in production! So, when i build the app, and deploy it, the data is not stored in localstorage! Only the ngrx-store-localstorage not working!
Rehydrate option is true!
Any idea?

P.S. Just checked right now, on Android i have same problem!

> Angular CLI: 10.1.3
Node: 12.16.3
OS: win32 x64
Angular: 10.1.3
Ivy Workspace: Yes

**Comment by BBlackwo** [comment]
Hi @Ruslancic I have not heard of this issue happening before now.

Can you provide a sample project to reproduce the issue?

**Comment by Ruslancic** [comment]
I using clear ngx-rocket starter kit, and i think this is the problem! Just tested it with clear angular repository, and all working fine! Sorry for  worng issue opened!
