### ISSUE TITLE
NgRx 11 compatibility

### ISSUE THREAD

**Issue by piotter121** [btroncone/ngrx-store-localstorage#178]
Hi,
When will you release version with NgRx 11 compatibility? If you need I would try make a PR for this.

**Comment by BBlackwo** [comment]
Hi @piotter121,

If you can do PR to update the peer dependency to support version 11 that'd be good.

You'll need to make sure you follow the commit message convention to do a major bump to version 11.

**Comment by BBlackwo** [comment]
The commit should be something like:

```
feat: update NgRx peer depency to v11

BREAKING CHANGE: update NgRx peer depency to v11
```
