### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Function calls are not supported.

### ISSUE THREAD

**Issue by nottinhill** [btroncone/ngrx-store-localstorage#18]
**The error message:**

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 6:54 in the original .ts file), resolving symbol authReducer in /Users/tyrion/devel/saveup-policy/src/app/saveup-common/common-core/common-auth/auth-store/auth-reducer.ts, resolving symbol CommonAuthModule.reducers in /Users/tyrion/devel/saveup-policy/src/app/saveup-common/common-core/common-auth/common-auth.module.ts, resolving symbol CoreModule.reducers in /Users/tyrion/devel/saveup-policy/src/app/core/core.module.ts, resolving symbol AppModule.reducers in /Users/tyrion/devel/saveup-policy/src/app/app.module.ts, resolving symbol AppModule.reducers in /Users/tyrion/devel/saveup-policy/src/app/app.module.ts, resolving symbol AppModule.reducers in /Users/tyrion/devel/saveup-policy/src/app/app.module.ts, resolving symbol AppModule in /Users/tyrion/devel/saveup-policy/src/app/app.module.ts, resolving symbol AppModule in /Users/tyrion/devel/saveup-policy/src/app/app.module.ts, resolving symbol AppModule in /Users/tyrion/devel/saveup-policy/src/app/app.module.ts

**My app.module.ts:** 

```
import {BrowserModule} from "@angular/platform-browser";
import {NgModule} from "@angular/core";
import {StoreModule, ActionReducer, combineReducers} from "@ngrx/store";
import {StoreDevtoolsModule} from "@ngrx/store-devtools";
import {CoreModule} from "./core/core.module";
import {AppSharedModule} from "./shared/shared.module";
import {CommonCoreModule} from "./saveup-common/common-core/common-core.module";
import {AppComponent} from "./app.component";
import {AppRoutingModule} from "./app-routing.module";
import {ClientModule} from "./client/client.module";

@NgModule({
    declarations: [
        AppComponent,
    ],
    imports: [
        BrowserModule,
        CommonCoreModule,
        CoreModule,
        AppRoutingModule,
        AppSharedModule,
        StoreModule.provideStore(AppModule.reducers())
    ],
    exports: [AppSharedModule],
    providers: [],
    bootstrap: [AppComponent]
})

export class AppModule {

    static reducers(): ActionReducer<any> {

        return combineReducers(Object.assign({},
            CoreModule.reducers(),
            ClientModule.reducers()
        ));
    }
}

```

**My auth-reducer:**

```
import { Action, ActionReducer } from '@ngrx/store';
import { AuthActionType } from './auth-action-type';
import { AuthModel } from '../shared/auth.model';
import { Deserializer } from '../../../common-shared/utils/deserializer';

export const authReducer: ActionReducer<AuthModel> = (state: AuthModel = undefined, action: Action) => {

  switch (action.type) {

    case AuthActionType.SET_AUTH:
      return action.payload ? Object.assign({}, Deserializer.deserializeFlat(action.payload, AuthModel)) : undefined;
    case AuthActionType.RESET_AUTH:
      return undefined;
    default:
      return state;
  }
};
```

Can anybody help?

**Comment by btroncone** [comment]
Please see this issue, I believe it's related. https://github.com/btroncone/ngrx-store-localstorage/issues/13

**Comment by nottinhill** [comment]
Seems like it. However I can't figure out how to apply https://github.com/btroncone/ngrx-store-localstorage/issues/13 to my problem.

**Comment by nottinhill** [comment]
I resolved this partially, but eventually thanks to https://github.com/ngrx/store/issues/190#issuecomment-252914335 but eventually downgraded to angular-cli.beta.20-4 which resolved all issues at once.
