### ISSUE TITLE
Setting state value to undefined

### ISSUE THREAD

**Issue by zygimantas** [btroncone/ngrx-store-localstorage#19]
If the state is set to ```undefined``` by reducer (case: logout), the value is not removed/update in localStorage. I am doing it wrong? The only option right now is to remove manually from the local storage in effect?

**Comment by ernestomancebo** [comment]
submitted a proposal under **Adding support to remove state when undefined #25** pull request

**Comment by btroncone** [comment]
Merged, closing this issue. Thanks @ernestomancebo!
