### ISSUE TITLE
Angular2 locked to beta 7

### ISSUE THREAD

**Issue by damienadermann** [btroncone/ngrx-store-localstorage#2]
Angular is locked to beta.7 in the package json. Is there a reason we can't make this greater than beta.7?

```
$ npm install
jobseekers-app@ /Users/damien/Develop/found/jobseekers-app
├── UNMET PEER DEPENDENCY angular2@2.0.0-beta.11
└── zone.js@0.6.5

npm WARN ngrx-store-localstorage@0.0.5 requires a peer of angular2@2.0.0-beta.7 but none was installed.
```

**Comment by damienadermann** [comment]
Also thanks for the package :+1:

**Comment by btroncone** [comment]
Good catch, there is no reason it needs to be locked to beta.7. I have updated and am publishing now. Thanks for the feedback! :smile:
