### ISSUE TITLE
Rehydrate with default state when no localStorage key?

### ISSUE THREAD

**Issue by radoslawroszkowiak** [btroncone/ngrx-store-localstorage#20]
Thank you for this really nice utility.
Is there any possibility that I can't figure out to provide default state for rehydration?

My problem:
I've got a state with "user" section, being and object with default values, i.e.:
```
{
  user: { token: null, loggedIn: whatever, ...other properties...},
  ...(other root keys)...
}
```
I'm syncing the whole user node. However, when the new user visits page and there's no localStorage "user" key, the user state after rehydration is `null`, instead of the object with user properties ` { token: null, loggedIn: 'whatever', ...other properties...}`. I'd like to have the object, not null.

Do you think this default, initial rehydration state when no localStorage key exists would be useful or I'm totally missing some other possibility (not hackish) to achieve what I want?

**Comment by btroncone** [comment]
Hello,

If I'm understanding correctly your best option may be to just set the default state in the user reducer (default param). That way if no local storage key exists for this item it will use your specified default state. The next time the user returns it will pick up the user info from local storage and everything should work correctly. 

Hope this helps!

**Comment by radoslawroszkowiak** [comment]
I thought yesterday that rehydration did not work correctly as I couldn't get it to work in jasmine tests. It simply turned out in the tests your "middleware" was not in use in some cases and it was not relevant to this this package. Actually, all is fine now, thank you.

Closing the issue - it's not really valid.
