### ISSUE TITLE
Support Angular 13

### ISSUE THREAD

**Issue by DerYeger** [btroncone/ngrx-store-localstorage#206]
`@ngrx/store` has already released `13.0.0-beta.0`.
It would be awesome to use this library with Angular 13 as well.

**Comment by BBlackwo** [comment]
Thanks for raising this @DerYeger. I think it makes sense to wait until `@ngrx/store` releases version 13 and then all the peer dependencies can be updated at once.

**Comment by j-be** [comment]
> wait until @ngrx/store releases version 13

`13.0.0` and `13.0.1` have been released yesterday and today respectively (https://www.npmjs.com/package/@ngrx/store?activeTab=versions)

**Comment by rdlabo** [comment]
I wanted to use it right away in Angular13, so I forked the pull request https://github.com/btroncone/ngrx-store-localstorage/pull/208 and built on my repository.

Please use it for temporary migration.

`npm i ngrx-store-localstorage@github:rdlabo/ngrx-store-localstorage#release/206`

and 

```ts
import { localStorageSync } from 'ngrx-store-localstorage';
↓
import { localStorageSync } from 'ngrx-store-localstorage/dist/lib';
```

**Comment by BramDecuypere** [comment]
Thanks @rdlabo , I've been watching this ticket for quite some time. And I can't keep on waiting for them to support Angular 13. It's been two months already since release date?

**Comment by xorph** [comment]
Any ETA for this issue?

**Comment by piotter121** [comment]
> Any ETA for this issue?

Spent almost 3 days to solve testing issues in #208 and didn't found solution for this module resolution problem. Wherefore moving my PR to draft PR.

**Comment by BBlackwo** [comment]
Sorry for the delay getting v13 support out. There was a module resolution problem that was stopping it from being merged in. 

Thanks to @piotter121 and @rdlabo for helping get this across the line!
