### ISSUE TITLE
init state patrly from localstorage and patrly from initial state

### ISSUE THREAD

**Issue by Liork1** [btroncone/ngrx-store-localstorage#21]
I would like to use localStorageSync in a way that it will partly pull the state from localstoarge and partly from the initial state definition.
 For example, assuming that this is my reducer:

```
export interface LoginState {
    permissions: Permissions [];
    userId: number;
    created: number;
};

```
And syncing it with localstorage like that:
` localStorageSync([{login: [‘permissions’]}], true)`

The problem is that the state contains now only the permissions object, without the default values I declared for userId & created.

Is there any way doing it?
What about the revive method mentioned in doc? I haven’t seen any example of how to use it.

Thanks in advance,
Lior

**Comment by ernestomancebo** [comment]
To set values to `userId` and `created` at the application bootstrap, I'd suggest to define the `INIT_ACTION` action constant and load the required data in the reducer as follow:

```ts
const INITIAL_STATE = '@ngrx/store/init';

export const permissions = (state = {}, action) => {
    switch (action.type) {
        // others action reducers

        case INITIAL_STATE:
            // Call the function that retrieves the userId and created
            return Object.assign({}, state, { userId: userId, created: created });

        // Others action reducers
    }
};
```
