### ISSUE TITLE
npm lib missing readme and license

### ISSUE THREAD

**Issue by baptistechardon** [btroncone/ngrx-store-localstorage#215]
Current version on the npm registry (13.0.0) appears to be missing readme or license:
![image](https://user-images.githubusercontent.com/24387436/159808538-3144c7a8-33dc-4edf-bf0c-6788dbbb03b7.png)

The latest version with a readme and a known license (MIT) on the registry seems to be 11.0

On github, the readme is still present, and a license field is in the github package.json.

**Comment by baptistechardon** [comment]
Fix proposition in PR : https://github.com/btroncone/ngrx-store-localstorage/pull/216

**Comment by BBlackwo** [comment]
:tada: This fix is included in version 13.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ngrx-store-localstorage/v/13.0.1)
- [GitHub release](https://github.com/btroncone/ngrx-store-localstorage/releases/tag/v13.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by BBlackwo** [comment]
Much better! :slightly_smiling_face: 
![Screenshot from 2022-03-30 15-03-08](https://user-images.githubusercontent.com/7598058/160749148-4fbe387c-6a68-441c-9acf-b6211729eb26.png)
