### ISSUE TITLE
Unable to save state to localStorage: DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'tempState' exceeded the quota.

### ISSUE THREAD

**Issue by Mohinesh27** [btroncone/ngrx-store-localstorage#221]
Hi, 
I am facing this issue please look into this. For more details please find the attached screenshot.

![image](https://user-images.githubusercontent.com/6978930/160997277-a92e572b-74fa-45c8-87fd-a01b070a8a88.png)

Please guide me how can I resolve it as I am newbie for Angular, NGRX with ngrx-store-localstorage.

**Comment by BBlackwo** [comment]
Hi @Mohinesh27 perhaps this will help? https://stackoverflow.com/questions/23977690/setting-the-value-of-dataurl-exceeded-the-quota

**Comment by BBlackwo** [comment]
Going to close this as I don't think it's related to this library.
