### ISSUE TITLE
Angular 14 dependency update

### ISSUE THREAD

**Issue by kevinsar** [btroncone/ngrx-store-localstorage#227]
Looks like there are peer dependencies on Angular 13 for the latest version of ngrx-store-localstorage. Had to use --force to install it after upgrading to Angular 14 as a workaround for now.

**Comment by soorireddy** [comment]
Have the following in package.json 

"overrides": {
    "ngrx-store-localstorage": {
      "@angular/common": "14.0.3",
      "@angular/core": "14.0.3",
      "@ngrx/store": "14.0.0"
    }
  },

**Comment by BBlackwo** [comment]
I raised a PR to upgrade to v14 but the tests are failing. That needs to be fixed before it can be merged.

**Comment by piotter121** [comment]
@BBlackwo Any idea when you could fix tests?

**Comment by BBlackwo** [comment]
Not sure when I'll have to time fix the build @piotter121. Would be happy for anyone to have a look if they have time #228.

**Comment by BBlackwo** [comment]
Fixed the build. Needed to upgrade `ts-node` to the latest.

Let me know if there are any issues with v14.
