### ISSUE TITLE
Encrypt the localStorage value

### ISSUE THREAD

**Issue by damsorian** [btroncone/ngrx-store-localstorage#23]
Hello!

Is it possible to encrypt the localStorage value?

Any idea how?

**Comment by ernestomancebo** [comment]
Hi @damsorian, on the pull request **Support for state encryption #28** there's a change to support such feature.

You'd be passing down a function on the key object as follow:
``localStorageSync([{ todos: { encrypt: encryptFunction, decrypt: decryptFunction } }, ... ]))``

**Comment by damsorian** [comment]
@ernestomancebo thank you very much!
