### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by chrisweight** [btroncone/ngrx-store-localstorage#234]
Be great if this could be updated to support NG 15.x, cheers!

**Comment by ahmadallw** [comment]
any new updates about updating to angular 15?

**Comment by SarcevicAntonio** [comment]
This is blocking us from upgrading to ng15 without forcing unclean peerdeps.

**Comment by SarcevicAntonio** [comment]
Can the PR be merged?

**Comment by BBlackwo** [comment]
Sorry for the delay on this. Had a few weeks off over the Christmas period. As you can see v15 has been published.
