### ISSUE TITLE
Upgrade to node v18

### ISSUE THREAD

**Issue by BBlackwo** [btroncone/ngrx-store-localstorage#250]
Node v16 reaches [EOL on 2023-09-11](https://nodejs.dev/en/about/releases/)

Required:
- [x] Update Circle CI image
- [x] Update .nvmrc
- [x] Update types
- [ ] Update any 3rd party libraries that require node 16 
- [x] Search for any other references to `16`

**Comment by jmetev1** [comment]
HI @BBlackwo. I made a pr. Let me know if it needs any changes.
