### ISSUE TITLE
error reading store data

### ISSUE THREAD

**Issue by sparachi** [btroncone/ngrx-store-localstorage#26]
I created the ngrx store something on the lines of this [article](https://www.pluralsight.com/guides/front-end-javascript/building-a-redux-application-with-angular-2-part-2)  and it is working fine. 

I'm using the localstorage option now `StoreModule.provideStore(
      compose(localStorageSync(['reducer']), combineReducers)({ reducer })`

my 'reducer' ( meta reducer )code looks like this 

`
const reducers = {
    profileData: fromProfile.reducer,
    collectionData: fromCollection.reducer
};

const combinedReducer: ActionReducer<State> = combineReducers(reducers);

export function reducer(state: any, action: any) {
    return combinedReducer(state, action);
}
`

when I dispatch post login actions to get the profile and update the store, it happens fine, and I also see the data in console.log and also store in local storage. By the time I navigate to the profile page and call Load profile action, I see errors. when I debug It looks the the `state` object is empty. 

my profile reducer looks like this 

`export interface State {
    profile: Profile;
};

const initialState: State = { profile: {} };

export function reducer(state = initialState, action: profile.Actions): State {
    console.log('in profile.reducer reducer() action is ', action);
    switch (action.type) {
        case profile.ActionTypes.FETCH_PROFILE_SUCCESS: {
            console.log('FETCH_PROFILE_SUCCESS ', action.payload);
            console.log('current state is ', state);

            if (state) {

                const newProfile: Profile = action.payload;
                newProfile.access_token = state.profile.access_token;

                let newState: State = {
                    profile: newProfile
                };
                console.log('new state is ', newState);
                return newState;
            }
            return state;
        }
        case profile.ActionTypes.LOAD_PROFILE_DATA: {
            console.log('LOAD_PROFILE_DATA ', action.payload);
            console.log('current state is ', state);
            if (state) {
                let newState: State = {
                    profile: state.profile
                };
                console.log('new state is ', newState);
                return newState;
            }
            return state;
        }`

I tried both options 

`StoreModule.provideStore(
      compose(localStorageSync(['reducer']), combineReducers)({ reducer })`

and 

`
StoreModule.provideStore(
      compose(localStorageSync([{ reducer: ['profileData'] }]), combineReducers)({ reducer })
    )
`

I am totally new to javascript and angular2. Any help would be appreciated.

**Comment by btroncone** [comment]
This seems to be a reducer issue, not an issue with this module if your store state is disappearing between actions. If you post a GitHub or Plunker link I could try to help if you haven't already figured it out, thanks!
