### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by meierw** [btroncone/ngrx-store-localstorage#260]
Since Angular 17 is out. Would be nice if it got support by this lib. Cheers 🙂

**Comment by JustDoItSascha** [comment]
For everyone who wants get it rid of the error messages while npm install without --force, do this:

```
"overrides": {
        "ngrx-store-localstorage": {
            "@angular/common": "$@angular/common",
            "@angular/core": "$@angular/core",
            "@ngrx/store": "$@ngrx/store"
        }
    }
```

**Comment by Neizan93** [comment]
Using Angular 17 SSR with ngrx-store-localstorage@16.1.0

./node_modules/ngrx-store-localstorage/fesm2022/ngrx-store-localstorage.mjs:1:0-34 - Error: Module not found: Error: Can't resolve 'deepmerge' in 'C:\Users\user\myapp\node_modules\ngrx-store-localstorage\fesm2022'

**Comment by prince-asamoah-amalitech** [comment]
> Using Angular 17 SSR with ngrx-store-localstorage@16.1.0
> 
> ./node_modules/ngrx-store-localstorage/fesm2022/ngrx-store-localstorage.mjs:1:0-34 - Error: Module not found: Error: Can't resolve 'deepmerge' in 'C:\Users\user\myapp\node_modules\ngrx-store-localstorage\fesm2022'

am facing similar error messages, it seems anular 17 ssr which uses node express can't access localStorage web api

**Comment by BBlackwo** [comment]
@Neizan93 @prince-asamoah-amalitech please raise a separate issue for the angular 17 ssr problem
