### ISSUE TITLE
What's version  of ngrx-store-localstorage is compatible with angular 16?

### ISSUE THREAD

**Issue by amalamalamal** [btroncone/ngrx-store-localstorage#262]

**Comment by haidar-h** [comment]
Check the release notes https://github.com/btroncone/ngrx-store-localstorage/releases try [v16.0.0](https://github.com/btroncone/ngrx-store-localstorage/releases/tag/v16.0.0) or [v16.1.0](https://github.com/btroncone/ngrx-store-localstorage/releases/tag/v16.1.0)

**Comment by dangrussell** [comment]
I'm using `~16.0.0` with Angular 16 for now, because switching to 16.1.0 gave me these warnings:

```
warning " > ngrx-store-localstorage@16.1.0" has incorrect peer dependency "@angular/common@^17.0.4".
warning " > ngrx-store-localstorage@16.1.0" has incorrect peer dependency "@angular/core@^17.0.4".
warning " > ngrx-store-localstorage@16.1.0" has incorrect peer dependency "@ngrx/store@^17.0.0".
```

**Comment by BBlackwo** [comment]
v16.1.0 should have been v17.0.0

I've just published v17.0.0 to hopefully minimise confusion.

**Comment by grubeninspekteur** [comment]
I ran into this too with npm update. If v16.1.0 is identical to v17.0.0, maybe you can deprecate 16.1.0? Transloco did it like this when they broke something in a patch version https://github.com/jsverse/transloco/issues/704

**Comment by BBlackwo** [comment]
Good idea @grubeninspekteur it's been deprecated https://www.npmjs.com/package/ngrx-store-localstorage/v/16.1.0?activeTab=versions 
![image](https://github.com/btroncone/ngrx-store-localstorage/assets/7598058/385d359a-930c-440e-b309-258d1bfb726d)

Will that stop `npm update` from updating to it now?

**Comment by grubeninspekteur** [comment]
@BBlackwo looks good, `ng update` for `^16.0.0` doesn't want to pull it anymore.
