### ISSUE TITLE
Angular 4 support

### ISSUE THREAD

**Issue by dojchek** [btroncone/ngrx-store-localstorage#29]
Hello,

With new version of angular, there is a warning for unmet dependency:
`warning "ngrx-store-localstorage@0.1.5" has incorrect peer dependency "@angular/core@^2.0.0-rc.5".`

It's not an urgent issue, but still would be nice to get rid of that warning.

Thanks

**Comment by nghiado** [comment]
This is actually a blocker issue to us so we can't upgrade our build to Angular4.
Can we fix this one soon?

**Comment by btroncone** [comment]
Hello,

Thanks for bringing this to my attention.

I should be able to get to this within the week, or I will merge a PR and publish if you want to submit a PR.

**Comment by kucharzyk** [comment]
Thanks for your work @btroncone

**Comment by relevantmedia** [comment]
I don't know if this is related. Getting and error from
```
    StoreModule.provideStore(compose(
      localStorageSync(['session'], true),
      combineReducers
    )(APP_REDUCERS))
```

Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an
exported function (position 12:42 in the original .ts file

**Comment by kucharzyk** [comment]
Any news about Angular 4 support?

**Comment by btroncone** [comment]
Updated package and removed outdated angular dep. 👍
