### ISSUE TITLE
Rehydrate dates

### ISSUE THREAD

**Issue by jasonwaters** [btroncone/ngrx-store-localstorage#3]
Great middleware, thanks for providing it!  

I've noticed that Dates are saved as strings in localStroage, since they must be.  But they are not rehydrated to actual dates when pulled out of localStorage.  Would be nice if the middleware detected date strings and Date.parse'd them.

**Comment by btroncone** [comment]
Thanks for the feedback! Let me look into this a bit to determine whether there is a way to efficiently handle this issue. I will keep you updated.

**Comment by btroncone** [comment]
This will be fixed for the next version to coincide with store v2 release (current storev2 branch). I will keep this open until new version is published. 👍

**Comment by jasonwaters** [comment]
Thanks!! Looking forward to it.

**Comment by btroncone** [comment]
This should now be working with the latest version.

**Comment by Fiontan** [comment]
Hi I'm seeing  a potential problem with moment dates. I cannot seem to find anything similar- does anyone know of an info?
