### ISSUE TITLE
localStorageSyncAndClean errors

### ISSUE THREAD

**Issue by jeffwhelpley** [btroncone/ngrx-store-localstorage#32]
When I use localStorageSync it works fine:

` localStorageSync(['auth'], true)`

But if I use localStorageSyncAndClean I get errors:

`localStorageSyncAndClean(['auth'], true, true)`

The error I get is:

```
Unhandled Promise rejection: Cannot read property 'currentSlot' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'currentSlot' of undefined
    at MapSubscriber.project (task.effects.ts:39)
    at MapSubscriber._next (map.js:77)
    at MapSubscriber.Subscriber.next (Subscriber.js:89)
    at State.BehaviorSubject._subscribe (BehaviorSubject.js:28)
    at State.Observable._trySubscribe (Observable.js:57)
    at State.Subject._trySubscribe (Subject.js:97)
```

Basically this is referring to when I do this:

```
    @Effect()
    goToSlotAfterChange$ = this.store
        .select(state => state.tasks.currentSlot)
        .map(slot => {
            return slot ?
                go(['/' + slot]) :
                go(['/'])
        });
```

So, it is saying `tasks` is null. It seems like it says this because the store was not initialized. So, the problem here is that when I use localStorageSyncAndClean, the store doesn't appear to be initialized. I am not sure why that is, but I can look further into this later.

**Comment by btroncone** [comment]
Thanks, I need to take a closer look at this logic.

Looping in @ernestomancebo

**Comment by btroncone** [comment]
@jeffwhelpley I'll take a look this weekend when I have a bit more time and provide update. Apologize for delay.

**Comment by jeffwhelpley** [comment]
no problem. I have a workaround for now to just use `localStorageSync(['auth'], true, window.localStorage, true)`

**Comment by jeffwhelpley** [comment]
btw...you may want to just consolidate to one function that takes in an object with all the options so you don't need to deal with function param order.

**Comment by btroncone** [comment]
Agree, that's a good change. This grew over time and should have been refactored. I'm going to try to give it some love over the next few days.

**Comment by jeffwhelpley** [comment]
Thanks. This is a great library and I think it is a perfect fit for many people that want to use ngrx. In fact, I will do my part to promote this lib.

**Comment by btroncone** [comment]
Thanks @jeffwhelpley ! 👍

**Comment by ernestomancebo** [comment]
Hi @btroncone, @jeffwhelpley. I'll gladly take a look into this and providing updates soon.

**Comment by btroncone** [comment]
Awesome @ernestomancebo, thanks! 👍🏻

**Comment by ernestomancebo** [comment]
@jeffwhelpley as I can see, you're passing a third parameter on `localStorageSyncAndClean(['auth'], true, true)`, which by definition when it's true it removes the key from the `localStorage` on a `undefined` state (not the store, just to be clear), that's what is causing the undefined error implying that you cannot access to the `currentSlot` property.

What I can't relate is how it works for you on `localStorageSync(['auth'], true, window.localStorage, true)` because the first approach is a wrapper that does the same as you do on the second.

Either way, I'm working on your suggestion to receive an object instead of a parameter list.

**Comment by btroncone** [comment]
Thanks for your hard work @ernestomancebo!

**Comment by btroncone** [comment]
Merged, please let me know if you encounter any further issues.

**Comment by btroncone** [comment]
Closing 👍
