### ISSUE TITLE
Storage conflicts

### ISSUE THREAD

**Issue by etatuev** [btroncone/ngrx-store-localstorage#36]
I've faced an issue with Storage conflicts when I had more than one application under same domain name, because sub apps had several same keys, which result to Storage keys overwrite upon `localStorageSync`.

Not sure if this should be handled by library, but I've created PR #37 with possible solution, custom serialize functions to make keys unique by using prefix or any other modifier.

What do you think about it?

**Comment by btroncone** [comment]
Thanks! I will get back to you soon. 👍

**Comment by qorsmond** [comment]
@btroncone I have exactly the same use case with sub apps on the same domain. Will PR #37 be merged or are you thinking of a different way in solving it?

**Comment by etatuev** [comment]
@btroncone 
This issue can be closed, I guess :)

**Comment by btroncone** [comment]
Closing :)
