### ISSUE TITLE
Can this pattern be used for large data? 

### ISSUE THREAD

**Issue by varghesep** [btroncone/ngrx-store-localstorage#39]
In my opinion, synching the store and the local storage will work for small ToDo app where the state is very minimum. But for a real application like a catalog management, you have thousands of products. You can't bring-in all those products to the store. The local storage can have all the products, but the store can have only the products which have been searched by the user.

What is your opinion on this?

**Comment by uitgewis** [comment]
It's a state store. You're going to have a bad time trying to use redux as a document store, IMO. I think the examples use it as such as a matter of convenience. 

Ideally one would use paginated responses from an endpoint, and update the state with that metadata. Saving all the records in the store(or simply in the browser) may quickly cause the app to become unresponsive while retrieving and modifying them.

I tend to use the state store as a pointer to locate the data that needs to be shown, for large datasets like product inventories, etc. You could store your current result set in a simplified state(id + name) for preloading, and even the current record if being modified, though.

**Comment by btroncone** [comment]
@varghesep You can also pick and choose which slices of state you wish to sync. Maybe you have a large store but only need a small section to by synced with local storage, this library will aid you in this regard. 👍
