### ISSUE TITLE
v2 Feature request: Sync slices of a state

### ISSUE THREAD

**Issue by frederikschubert** [btroncone/ngrx-store-localstorage#4]
I would like to store only parts of the state that is handled by one reducer. This could be implemented by allowing nested keys like `todos.done`.

**Comment by btroncone** [comment]
This scenario should now be accommodated. 👍

**Comment by wesselvdv** [comment]
@btroncone 

This seems to be broken now. Can't define it.

**Comment by oliveiracdz** [comment]
Hi, @wesselvdv!

Like said in [PR](https://github.com/btroncone/ngrx-store-localstorage/pull/6#issue-162598656). this is the correct sintax: `localStorageSync([{todos: ['done'] }, ... ])`

**Comment by wesselvdv** [comment]
@oliveiracdz You're right I figured this out on my own. Thanks for the reply though!
