### ISSUE TITLE
ngrx 4 + prod flag

### ISSUE THREAD

**Issue by dojchek** [btroncone/ngrx-store-localstorage#43]
I was able to integrate localstorage and it works when running with `ng serve'.
However, running the `ng build --prod`  I get the following exception:
```
ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler
```

The way I add a localstoragesync is (app.module.ts):
```
StoreModule.forRoot(reducers , {
       metaReducers: [
         localStorageSync({keys: ['filter', 'auth']})
       ]
     })
```

As soon as I remove metaReducers, it builds successfully

**Comment by dojchek** [comment]
This is likely due to this issue:
[link](https://github.com/ngrx/platform/issues/116)

**Comment by dojchek** [comment]
I debugged a bit and seems like the issue is with arrow functions. Once I convert the `localStorageSync` like in the following [GIST](https://gist.github.com/dojchek/c27ec375758417ba38d569fe455f5ec9)
it no longer throws error..

**Comment by kevfuzz** [comment]
Same issue. Any ETA on when this might be fixed?

**Comment by bradyshutt** [comment]
I can't even get `ng serve` to run without the "Error encountered resolving symbol values statically..." error, and a failed compilation. 

After the failed compilation, triggering a re-compilation (ie, changing a file as ng serve watches for file changes) results in a successful compile. `ng serve` seems to only give this error on the initial compilation.

**Comment by maxisam** [comment]
@kevfuzz technically, this doesn't need to be fixed. 

use this following way to wrap `localStorageSync` and put it into an array for `metaReducers`. You are good to go.

```
export function localStorageSyncReducer(reducer: ActionReducer<any>): ActionReducer<any> {
  return localStorageSync({ keys: ['user'], rehydrate: true })(reducer);
}
````

**Comment by kevfuzz** [comment]
Perfect, thanks.

**Comment by dojchek** [comment]
Nice! Thank you @maxisam 
Closing this issue - It would definitely be useful to add this to docs for future reference
