### ISSUE TITLE
Docs and status for use in ngrx 4.0

### ISSUE THREAD

**Issue by bufke** [btroncone/ngrx-store-localstorage#45]
I'm trying (and failing) to understand #43 and #41. The readme mentions `StoreModule.provideStore` which no longer exist. How should this project be used in 4.0? Is it currently not actually compatible and some "very simplistic version as a temporary solution" workaround exists?

**Comment by btroncone** [comment]
@bufke Hello, I apologize for the delay. I have not had the bandwidth lately to update this module. I will do it as time allows or would gladly accept a PR. 👍

**Comment by bufke** [comment]
Understood. I'll let you know if I find the time. I'd also be happy paying you or anyone else market rate for the work too.

**Comment by papaiatis** [comment]
+1, need an update for supporting ngrx 4.0
