### ISSUE TITLE
Is there a way to throttle the call to local storage to prevent too many save actions

### ISSUE THREAD

**Issue by imolorhe** [btroncone/ngrx-store-localstorage#46]
Currently, every change made in my app automatically saves the state to the local storage. This includes when typing text into the editor. It would be more appropriate instead to throttle the calls to save the changes in the storage. Is there a way to do this with this package?

**Comment by btroncone** [comment]
@imolorhe There is not currently a way within this module. However, throttling or debouncing can be done at the action level when using store. 

For instance, in your text example you could `debounceTime` on `valueChanges` of an input, only sending actions when an appropriate duration has passed.

Hope this helps! 👍

**Comment by imolorhe** [comment]
Thanks
