### ISSUE TITLE
v2 Feature request: Add option for immutable.js

### ISSUE THREAD

**Issue by frederikschubert** [btroncone/ngrx-store-localstorage#5]
Because immutable.js data structures can not be serialized and deserialized properly using `JSON`, an option would be useful that enables [transit-immutable-js](https://github.com/glenjamin/transit-immutable-js) for the serialization and dehydration.

**Comment by frederikschubert** [comment]
I have been thinking about this and maybe it would be better to not depend on that module directly with this lib but simply create the option for the user to provide his/her own serialization/rehydration function. The default would then still be `JSON.parse`/`JSON.serialize`.

**Comment by btroncone** [comment]
> maybe it would be better to not depend on that module directly with this lib but simply create the option for the user to provide his/her own serialization/rehydration function

This is probably the route I will go. I have a couple other things I am finishing up at the moment but will circle back after and implement this functionality. 👍

**Comment by btroncone** [comment]
This should now be accommodated. 👍

**Comment by mpetkov** [comment]
@btroncone - When you have time, could you please add an example of how to use this with a reducer that used Immutable.js?
