### ISSUE TITLE
Use ngrx-store-localstorage 0.2.x with ngrx V 2

### ISSUE THREAD

**Issue by AnnaLinnIsabelle** [btroncone/ngrx-store-localstorage#50]
Hi!
I am using ngrx version 2, can I still use the latest versoin of ngrx-store-localstorage? 

cheers

**Comment by btroncone** [comment]
Yes, you will just need to follow the config from prior versions. The only thing that changed was how you configure the localStorage meta-reducer. 

You can check out the README history for setup with previous versions. Let me know if you have any additional questions, good luck! 👍
