### ISSUE TITLE
Where is the example?

### ISSUE THREAD

**Issue by papaiatis** [btroncone/ngrx-store-localstorage#52]
I can't seem to find any examples on how to use this module. Is it missing? 
Or is it really just these couple of lines?

```
export function localStorageSyncReducer(reducer: ActionReducer<any>): ActionReducer<any> {
  return localStorageSync({keys: ['todos']})(reducer);
}
const metaReducers: Array<ActionReducer<any, any>> = [localStorageSyncReducer];
```

**Comment by wizardnet972** [comment]
Yes. nothing more :)

**Comment by papaiatis** [comment]
Nice. At least this isn't that much complicated than ngrx store itself. 
However some slightly change in the Readme file would be great to clearly mark where is the example code. I got confused the first time.

**Comment by btroncone** [comment]
@wizardnet972 Thanks for responding 👍

**Comment by ilennert** [comment]
Well ok, that's one scenario.  What if you have already defined metaReducers as:
```
export const metaReducers: MetaReducer<any>[] = !environment.production
  ? [storeFreeze]
  : [];
```
