### ISSUE TITLE
Storage on demand

### ISSUE THREAD

**Issue by wizardnet972** [btroncone/ngrx-store-localstorage#53]
Let's say I want to save my data from the Store to Storage. but after some logic time something change and I don't want to save to the Storage.

For example: "Remember me" at login.
After login I get the token then I save it to the Store (and to the Storage).
But when I turn off "Remember me" I want to save  the token to the Store (and **NOT** to the Storage)

**Comment by btroncone** [comment]
Thanks for your question! There is currently not a way to conditionally sync slices of states, this logic would have to reside elsewhere. This may be worth considering for a future release. 👍
