### ISSUE TITLE
Use sessionStorage option

### ISSUE THREAD

**Issue by akrueger** [btroncone/ngrx-store-localstorage#55]
Would there be any major hurdles in having a config option to use `sessionStorage` rather than `localStorage`?

If that is what this option does, then feel free to close. 

```storage (optional) Storage: Specify an object that conforms to the Storage interface to use, this will default to localStorage.```

Thanks!

**Comment by akrueger** [comment]
I gave this a try and it worked perfectly, thanks!

**Comment by dcanning** [comment]
@akrueger What did you pass in for the storage option to get this to work with session storage?
