### ISSUE TITLE
using ionic, how to set storage to ionic storage insted of  local Storage

### ISSUE THREAD

**Issue by hackeurtalibe** [btroncone/ngrx-store-localstorage#62]

**Comment by brettatoms** [comment]
@hackeurtalibe see #48

**Comment by okonon** [comment]
@hackeurtalibe use ionic[ specific package](https://github.com/natural-apptitude/ngrx-store-ionic-storage) that is inspired by this repo

**Comment by tanyagray** [comment]
Closing due to alternative package recommendation [ngrx-store-ionic-storage](https://github.com/natural-apptitude/ngrx-store-ionic-storage). Thanks @okonon 👍
