### ISSUE TITLE
ngrx-store storage for nativescript?

### ISSUE THREAD

**Issue by cnoter** [btroncone/ngrx-store-localstorage#66]
Can I use this library to work with my nativescript app by writing some "custom storage" code(conforming storage api)?  Actually, redux-persist(https://github.com/rt2zz/redux-persist) has a support for react-native, can we have that for nativescript? or and sample DEMO code for this? Please Help:)

**Comment by csutorasr** [comment]
This has nothing to do with this repo. Here is an implementation of localstorage for nativescript: https://github.com/NathanaelA/nativescript-localstorage .

**Comment by bufke** [comment]
I can confirm this project works great with Nativescript and nativescript-localstorage. nativescript-localstorage works like a polyfill - there is nothing special you need to do to make this project work with it.

**Comment by tanyagray** [comment]
Closing as @bufke can confirm this project works with nativescript. Thanks 👍
