### ISSUE TITLE
Remove Angular2 dependency?

### ISSUE THREAD

**Issue by jFensch** [btroncone/ngrx-store-localstorage#7]
I'm not sure the ng2 dependency is even needed.

**Comment by btroncone** [comment]
It's not, I removed from ngrx-store-logger and will cut a new version of local-storage soon. Thanks! :+1:

**Comment by ganeshpms** [comment]
Is there any side effect if we still use this package with angular-rc4?

**Comment by btroncone** [comment]
Nope, should work fine.

**Comment by btroncone** [comment]
Angular dependency has been removed. :+1:
