### ISSUE TITLE
Notification/callback after state was loaded?

### ISSUE THREAD

**Issue by blissi** [btroncone/ngrx-store-localstorage#74]
Hallo,
this is not a problem with your library, just a question how I could achieve the following:
I am using ngrx and your lib to store auth information to local storage. When the user comes back to the page, the auth infos are reloaded from local storage. My application isn't a classic REST application though - all communication goes over a websocket. Thus, I would have to connect the websocket after the auth info has been restored from local storage. Is there some notification/callback where I can check if the auth state was loaded and connect the websocket?

**Comment by okonon** [comment]
@blissi you can subscribe to hydraged slice of the store:
`this.store.select('hydrated').subscribe(...)`

**Comment by blissi** [comment]
@okonon Thanks!
