### ISSUE TITLE
Objects become Json Objects

### ISSUE THREAD

**Issue by 11mb** [btroncone/ngrx-store-localstorage#8]
I'm storing js objects into the ngrx store.. This is working OK, but when these are injected back by the localstorge library these aren't objects anymore but json objects. I want to be able to turn these json objects back to my own objects just before they are injected back into the store.  

Is there any callback function, or point where I can do this?

**Comment by btroncone** [comment]
Could you provide a more detailed explanation or example? The state rehydrated by this module should mirror the state in your store at the point the last action was dispatched. I would be glad to help but am a bit confused by the behavior you are looking for. Thanks! :+1:

**Comment by 11mb** [comment]
Thanks for your reply. I'm not sure if what I'm doing is a best practice or not, but I'm storing Objects like such in the store:

`let myObject = new DataObject();`

This dataobject looks like this for example:

    class DataObject {
       public value1:string = 'hello';
       public value2:string = 'world';

      myFunction() {
          return this.value1 + ' ' + this.value2;
       }
    }

When this objects are stored in localstorage, and retrieved again these objects become JSON objects:

{'value1':'hello', 'value2':'world'}

So what I like to be doing: just before ngrx-store-localstorage injects the objects from the local storage into the store is would like to be able to 'cast' the JSON into the objects again so I can make use of the functions.

I am thinking, if this is not possible, to only store JSON objects into the store and add for each object type a helper class.

    interface DataObject {
       public value1:string;
       public value2:string;
    }

    class DataObjectHelper {
        myFunction(object:DataObject) {
             return object.value1 + ' ' + object.value2;
        }
    }

**Comment by btroncone** [comment]
I see, thanks for the explanation! Due to time constraints I do not have plans to implement this functionality at this time but I would gladly look over a PR if you would like to take a shot. I will also keep this on my radar for the future if you do not get an opportunity yourself. I am closing this issue for now but will keep an eye out. :+1:
