### ISSUE TITLE
NgRx store IndexedDB?

### ISSUE THREAD

**Issue by GuillaumeUnice** [btroncone/ngrx-store-localstorage#87]
Is there a way or an adapter to use indexedDB instead of the localstorage? Because, I have a memory limitation issue.

Is there a way to just change that or not easily?

Thanks for all

**Comment by yannickglt** [comment]
Hi,
You might want to use [ngrx/db](https://github.com/ngrx/db) instead? It's still experimental but looks to have a lot of users.

**Comment by GuillaumeUnice** [comment]
Yep I know but like you said it's experimental (authors don't want we use it) and is not so popular like ngrx-store-localstorage, I even the impression it's deprecated no owner activity for some time.

I don't really know if it contains the same functionnality today?

**Comment by arutkowski00** [comment]
It'd be nice if ngrx-store-localstorage could support localForage/localForage.

**Comment by LeoCreer** [comment]
https://github.com/pubkey/rxdb

**Comment by radacovsky** [comment]
Hi. 
I have just published this
https://github.com/radacovsky/ngrx-store-idb

It is based on this library. I hope that the attribution is ok. The license stayed the same: MIT.

**Comment by BBlackwo** [comment]
@radacovsky thanks for the attribution! 

I'm going to close this issue as it looks like there are several alternative libraries for Indexed Db storage.
