### ISSUE TITLE
If a null is stored, it should be looked upon as an object

### ISSUE THREAD

**Issue by filipvh** [btroncone/ngrx-store-localstorage#89]
If null is stored in a separate key/value it should be considered an object.
Otherwise it will become a string :(

See pull request
This is a fix for the bug
#88

**Comment by BBlackwo** [comment]
This should probably be closed as that PR was merged ages ago 😄

**Comment by BBlackwo** [comment]
@filipvh can you close this issue now?

**Comment by BBlackwo** [comment]
Closing this as that PR with the fix was merged.
