### ISSUE TITLE
v2 Feature Request: Option to sync to sessionStorage instead of localStorage

### ISSUE THREAD

**Issue by kurigohan** [btroncone/ngrx-store-localstorage#9]
It would be nice to have the option between syncing to localStorage or sessionStorage.

**Comment by btroncone** [comment]
I will consider adding this, thanks :+1:

**Comment by dwgray** [comment]
@btroncone:  I have refactor that takes an optional parameter of type Storage (default value localStorage) in the stuff I'm playing with to try to get testing in.  I'm happy to add that in if I can get over the testing isssues...

**Comment by btroncone** [comment]
Sounds great! :+1:

**Comment by btroncone** [comment]
This should now be accommodated. 👍
