### ISSUE TITLE
Update to Angular 6

### ISSUE THREAD

**Issue by MrSnappingTurtle** [btroncone/ngrx-store-localstorage#90]
Angular 6 is out. Is there any ETA on a new release of `ngrx-store-localstorage`?

 ~in the release candidate phase and should be stable soon. Would be nice if there was a beta release of `ngrx-store-localstorage` that targets the latest Angular RC.~

https://github.com/angular/angular/releases

**Comment by arutkowski00** [comment]
Version 5.0.0 actually works for me without any hassle. If I am not wrong, a simple test and version increment would be enough.

**Comment by k-schneider** [comment]
Ngrx 6.0.x final is now out so hopefully this update can happen soon?

**Comment by StAn187** [comment]
@arutkowski00 I don't think this is an angular 6 issue, it's AOT afaik. I did a test upgrade to Angular 6 and ngrx store 6 and it seems to work. 

I attach the meta reducer via the META_REDUCERS provider token (as documented [here](https://github.com/ngrx/platform/blob/master/docs/store/api.md#injecting-meta-reducers)) like this

    providers: [
        // ...
        { provide: META_REDUCERS, useFactory: metaReducerFactory },
    ],

where `metaReducerFactory` is a function returning `[localStorageSyncReducer]` (`localStorageSyncReducer` can be found in the "Usage -> UPDATE FOR NGRX 4" section of the README.md)

**Comment by arutkowski00** [comment]
@StAn187 Yep, I figured it out by myself, I forgot to update.

**Comment by StAn187** [comment]
@plisovyi, yes. Seems so. I updated to Angular 6 two weeks ago and everything works well.

**Comment by MrSnappingTurtle** [comment]
Closing since this was fixed under #95
