### ISSUE TITLE
Encrypt supported?

### ISSUE THREAD

**Issue by inthegarage** [btroncone/ngrx-store-localstorage#99]
I am trying to use the encrypt functionality that is meant to be in the main branch.
However when I supply the following line to the localStorageSync, the config is not recognised:

`  return localStorageSync({keys: ['bookings'],  bookings: { encrypt: encryptFunction, decrypt: decryptFunction } })(reducer);`

Looking at the interface LocalStorageConfig, I don't see this mentioned. What is the current status?
Many thanks.

**Comment by ernestomancebo** [comment]
The keys array only contains the state name, you should specify the bookings object inside the array. See bellow:

`return localStorageSync({ keys: [bookings: { encrypt: encryptFunction, decrypt: decryptFunction } }])(reducer);`

**Comment by inthegarage** [comment]
@ernestomancebo Thanks very much.

**Comment by inthegarage** [comment]
@ernestomancebo  That is working me, thank you.
